services:
  chromadb-dev: 
    image: chromadb:dev2
    container_name: chromadb_poc
    network_mode: host  
    volumes:
      - ../:/proj/     
      - ~/.ssh:/home/user/.ssh # forward ssh keys (linux-specific)
      - /tmp/.X11-unix:/tmp/.X11-unix      
    environment:
      - DISPLAY=$DISPLAY
      - MPLBACKEND=TkAgg
    stdin_open: true
    tty: true
